version: '3'

services:
  redis:
    image: 'redis:3.2-alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  web:
    build: './nodejs'
    command: npm run dev
    depends_on:
      - 'redis'
    env_file: 
      - '.env'
    ports:
      - '80:8000'
    volumes:
      - './nodejs:/app'

volumes:
  redis: {  }

networks:
  front-tier:
  back-tier: