version: '3'

services:
  redis:
    image: 'redis:5.0.3-alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'
    networks:
      - back-tier

  db:
    image: mysql:5.7.12
    # construye: './mysql'
    restart: always
    container_name: db-mysql
    environment:
      MYSQL_DATABASE: 'hsbcnet_testing'
      # Usar root como contraseña es opcional
      MYSQL_USER: 'test'
      # Se puede usar la contraseña que se desee
      MYSQL_PASSWORD: '11501112'
      # Contraseña para accesar al root
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Puerto expuesto> : < puerto MySQL que se ejecuta dentro del contenedor>
      - '3306:3306'
    expose:
      # Abre el puerto 3306 en el contenedor
      - '3306'
    # Aquí se conservarán nuestros datos
    volumes:
      # - db-data:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
    networks:
      - back-tier

  web:
    build: './nodejs'
    env_file:
      - '.env'
    ports:
      - '80:8000'
    volumes:
      - './nodejs:/app'
    networks:
      - front-tier
      - back-tier
    depends_on:
      - redis
      - db

volumes:
  redis:
    # db-data:

networks:
  front-tier:
  back-tier:
